# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] # list of lists

In [8]:
np.array(my_mat) # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10) # 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5)) # pass in a tuple for 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.linspace(0,5,10) #10 evenly spaces points from 0-5 (1D)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.linspace(0,5,100) #100 evenly spaces points from 0-5 (1D)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5) # 0-1 random number 1D

array([0.88912175, 0.3245831 , 0.45175805, 0.49305511, 0.12406986])

In [23]:
np.random.rand(5,5) # 0-1 random number 2D

array([[0.85960075, 0.93029615, 0.68762791, 0.03113199, 0.09094699],
       [0.76251013, 0.28148809, 0.70608224, 0.79571599, 0.24799652],
       [0.14558098, 0.27544133, 0.75656353, 0.98991788, 0.85716377],
       [0.29219119, 0.58208679, 0.65362267, 0.46939721, 0.39027938],
       [0.46546655, 0.61841215, 0.0799445 , 0.79546998, 0.89014538]])

In [24]:
np.random.randn(2) # random number from a Gaussian distribution 1D

array([-1.0893161 , -1.14828996])

In [25]:
np.random.randn(2,2) # random number from a Gaussian distribution 2D

array([[ 0.4778496 , -1.93574097],
       [ 0.05026831, -0.95460893]])

In [26]:
np.random.randint(1,100) # one random integer (low:incusive, high: exclusive)

3

In [27]:
np.random.randint(1,100,10) # 10 random integer (low:incusive, high: exclusive)

array([67, 57, 82, 85, 41, 82, 57, 96, 62, 20])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(1,50,10)

In [31]:
ranarr

array([29,  4, 31, 34, 13, 13, 47, 28, 34,  5])

In [33]:
arr.reshape(5,5) # turns the 1D array into a 2D array (must be able to fill)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

47

In [36]:
ranarr.min()

4

In [37]:
ranarr

array([29,  4, 31, 34, 13, 13, 47, 28, 34,  5])

In [38]:
ranarr.argmax() #index of max value

6

In [39]:
ranarr.argmax() #index of min value

1

In [40]:
arr.shape #shape of array (1D)

(25,)

In [41]:
arr2 = arr.reshape(5,5)

In [45]:
arr2.shape #shape of array (2D)

(5, 5)

In [44]:
arr.dtype #data type

dtype('int64')

In [46]:
from numpy.random import randint

In [47]:
randint(2,50) # np no longer needed

38

# Indexing and Selection

### 1D Arrays

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[8]

8

In [53]:
arr [1:5]

array([1, 2, 3, 4])

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
slice_of_arr = arr[0:6]

In [62]:
slice_of_arr[:] = 99

In [63]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [64]:
arr #also changes the original!!!!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
arr_copy = arr.copy() #use copy method instead!!!

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
arr_copy[:] = 100

In [69]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### 2D arrays

In [71]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[0][0] #row then column!!

5

In [75]:
arr_2d[1][1]

25

In [76]:
arr_2d[0] #whole column

array([ 5, 10, 15])

In [77]:
arr_2d[1,2] #comma notation (recommended)

30

In [78]:
arr_2d[:2,1:] #selecting a sub array

array([[10, 15],
       [25, 30]])

In [84]:
arr_2d[1:][:2] # DO NOT USE DOUBLE BRACKETS FOR THIS REASON!!

array([[20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[1:,:2] # This was the desired result and not the same as above!

array([[20, 25],
       [35, 40]])

### Conditional Selection

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 5 #returns an array of bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr > 5

In [90]:
arr[bool_arr] # only returns elements where true

array([ 6,  7,  8,  9, 10])

In [91]:
arr[arr > 5] # More common notiation

array([ 6,  7,  8,  9, 10])

In [92]:
arr[arr < 3]

array([1, 2])

In [93]:
arr_2d2 = np.arange(50).reshape(5,10)

In [94]:
arr_2d2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [95]:
arr_2d2[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [96]:
arr_2d2[2:,7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [99]:
arr_2d2[arr_2d2 > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

# Operations

In [100]:
arr = np.arange(0,11)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr + arr # element by element addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [105]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [107]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [108]:
1/0

ZeroDivisionError: division by zero

In [109]:
arr / arr # numpy will just give a warning and return a null value

/Users/tweedles/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
1/ arr #this will return an infinity instead

/Users/tweedles/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [112]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [113]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [114]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [115]:
np.max(arr)

10

In [119]:
arr.max() # same as above

10

In [117]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [118]:
np.log(arr) # log(0) returns inf

/Users/tweedles/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])